---
Title: Build a robot
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Build a robot
description: Learn how to position images to design your own robot
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
  completion:
  - internal
- title: Step 4
- title: Step 5
  challenge: true
  completion:
  - external